worker_processes 1;
error_log stderr;

events {}

http {
    access_log ./tmp/nginx.access.log;
    server {
        listen 5555;

        location / {
            proxy_pass http://unix:./tmp/classy.sock:;
            proxy_http_version 1.1;
        }
    }
}
