worker_processes 1;
access_log ./tmp/nginx.access.log;
error_log ./tmp/nginx.error.log;

events {}

http {
    server {
        listen 5555;

        location / {
            proxy_pass http://unix:./tmp/classy.sock:;
            proxy_http_version 1.1;
        }
    }
}
