worker_processes 1;
error_log stderr;

events {
}

http {
    access_log ./tmp/nginx.access.log;
    types {
        text/css css;
    }
    server {
        listen 5555;

        location /static {
            root ./;
        }

        location / {
            proxy_pass http://unix:./tmp/http.sock:;
            proxy_http_version 1.1;
        }
    }
}
